### PR TITLE
Fix lots.json to validate against the schema

### PR DESCRIPTION
**Pull request by yolile**

### CODE REVIEW

**Comment by yolile** [comment]
Closes #4

**Comment by timgdavies** [comment]
That solves the uri issue, though I've noticed we also are missing the version (1.1) and extension (linking to lots) from the example. 

http://standard.open-contracting.org/validator/data/4b4e79c4-152c-4ddf-a20d-bb5b5751b208 (switched to 1.1, as it defaulted to validating 1.0 as there was no version field)

Possible to add those too?

**Comment by yolile** [comment]
Done, also I:
    - Change the relatedLots array (/release/tender/item) to relatedLot string.
    - Change maximumValue field type from integer to Value object

And now it is validating against both versions

**Comment by timgdavies** [comment]
Great work thanks @yolile 

Will add a note to the extension template development plans to see if we could have better testing by default for extensions.

**Pull request merged**
